---
spring:
  application:
    name: lab-4-verb
  profiles:
    active: verb
  config:
    import: optional:configserver:http://localhost:8001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8010/eureka/

#words: ran,knew,had,saw,bought

server:
  port: ${PORT:${SERVER_PORT:0}}